---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role oauth_client_setup
#
# Overview:
#
#
# Dependencies:
#
#
# Example play:
#
#

- name: Create OAuth2 django-oauth-toolkit Backend Service Applications
  shell: >
    {{ COMMON_BIN_DIR }}/python.edxapp {{ COMMON_BIN_DIR }}/manage.edxapp lms --settings={{ COMMON_EDXAPP_SETTINGS }}
    create_dot_application
    --grant-type client-credentials
    --client-id {{ item.backend_service_id }}
    --client-secret {{ item.backend_service_secret }}
    {{ item.name }}-backend-service
    {{ item.username }}
  become_user: "{{ edxapp_user }}"
  environment: "{{ edxapp_environment }}"
  with_items: "{{ oauth_client_setup_oauth2_clients }}"
  when:
    - item.name != 'None'
    - item.backend_service_id is defined
    - item.backend_service_id != 'None'
    - item.backend_service_secret is defined
    - item.backend_service_secret != 'None'
